### ISSUE TITLE
Question on heart_pulse_blood_flowing.ino example

### ISSUE THREAD

**Issue by francoisoudot** [marmilicious/FastLED_examples#1]
Hey Marc,
Sorry for reaching out to you through github - but couldn't find a better way to do it...
I have been trying to figure out something in your sketch heart_pulse_blood_flowing.ino example:
On line 50 you have:
uint8_t bloodVal = sumPulse( (5/NUM_LEDS/2) + (NUM_LEDS/2) * i * flowDirection );
How is (5/NUM_LEDS/2) + (NUM_LEDS/2) calculated?
Thanks for your feedback - you can send me an email at francois.oudot@gmail.com

**Comment by marmilicious** [comment]
Hello @francoisoudot 
Honestly I'm not actually sure where the 5 comes from in the 5/NUM_LEDS/2 part.  Chris Thodey's original setup had 78 pixels and he might have determined that a multiplier of 5 gave the "correct look" when taking into consideration the average time for a heartbeat QRS interval (or maybe it was the heartbeat QT interval?).

With his 78 pixels that first part would give around  5/78/2 = .128
With my 32 pixel example that first part would give  5/32/2 = .3125

Of course if you only had 2 pixels or 200 pixels it would be very different (giving 5 and .05 respectively).  If you aren't getting a nice "heartbeat" look, maybe try changing that multiplier a tiny bit?
Also try setting your NUM_LEDS to 32 to see the heartbeat look I'm getting if you didn't try that yet.

Here's the original G+ thread (which also has Mark's thoughts and Chris's code) which I based mine on.
https://plus.google.com/+ChrisThodey/posts/UdyqYt318gF

Let me know what you discover and I would be curious to know how may pixels you have in your setup.

And of course feel free to make a new FastLED G+ post too showing off what you're working on or if you want more people to see your question.  (If you post in that old G+ thread only those that originally commented would be likely to see it, so probably best to start a new one.)
Cheers,
marc

**Comment by francoisoudot** [comment]
Thanks so much for your feedback! Will share you the result of my
experience.
The project is for an art exhibition - will share pictures!

Francois Oudot
+1 510 283 1943

2017-04-05 20:14 GMT-07:00 Marc Miller <notifications@github.com>:
