### ISSUE TITLE
adding extra segments

### ISSUE THREAD

**Issue by dheather** [marmilicious/FastLED_examples#2]
hey mate, sorry for reaching out, just wondering if you can give me some input into adding a 3rd segment. 

Cheers

**Comment by marmilicious** [comment]
Hello @dheather   Do you have a link to something?  Not sure what you're asking about.

**Comment by dheather** [comment]
Hi mate. 

Pretty.l much using your code to make a scoreboard and att buttons ETC 

Just hoping you can help me with some code to add a 3rd to your 7-segments 2 digit example.

**Comment by marmilicious** [comment]
Ah understood.  Sure, here's a 3 digit version for you.  (I hope I got it right-- don't actually have a 3 digit setup to test on.)  Please let me know how it goes.
https://github.com/marmilicious/FastLED_examples/blob/master/CRGBSet_7segment_3digits.ino
Cheers

**Comment by marmilicious** [comment]
@dheather  So was that useful at all?

**Comment by dheather** [comment]
Sorry mate. I’ve been flat out and haven’t had a chance to use the code yet. I’ll try get it going today. Will advise how it went. :)
